### ISSUE TITLE
Workers Misconfiguration

### ISSUE THREAD

**Issue by ph4t0o0o0om** [Blair2004/NexoPOS-4x#151]
NexoPOS is unable to run tasks correctly. This happens if Queues or Tasks Scheduling aren't configured correctly. 

After I successfully setup and fix the "CSRF token mismatch " this error pops up on notification . how to fix this sir?

**Comment by Blair2004** [comment]
Hi, 
NexoPOS 4.x needs to have Cron configured so that i can perform some tasks behind the scene. To fix this issue, you need to configure the CRONjob on your installation. 

If you're running on Windows, there is a "cron.js" at the root of the installation, you'll have to make nodejs execute that file. From the CLI, you can therefore type "node cron.js" or use an application that will do that command for you: https://www.electronjs.org/apps/alarm-cron

If you're on Ubuntu, you'll have to configure CRON as mentioned here : https://laravel.com/docs/8.x/scheduling#running-the-scheduler

**Comment by Blair2004** [comment]
Closed for inactivity
