### ISSUE TITLE
Multiple unit products go blank after update and cant upload files or images.

### ISSUE THREAD

**Issue by loomitz** [Blair2004/NexoPOS-4x#312]
hi, a couple of months ago I decided to buy Nexopos 4 in Envato, installing it was difficult but after a while I managed to put it into operation. 

Today I made the mistake of trying to update, replace the files with the new ones and then run: "composer update".

 When I finish my installation I stop working properly, I tried everything before replacing the files I saved a copy of my current files, rollingback to my originals files fix one of my two problems.

1.- The products with multiple units stopped appearing correctly only the unfocused layer appeared

2.- stop being able to upload files every time I upload one it seems that it is damaged attached images.

![image](https://user-images.githubusercontent.com/20279105/134172613-f8b518c4-13bb-42c8-9e13-d24dc912dd29.png)

![image](https://user-images.githubusercontent.com/20279105/134172637-f47e170a-85c3-4fa0-a6db-ddbef6962a5d.png)

I would love to be able to update because in the last version (nexo 3) I used the fast product a lot and I know that in the last update you guys added it, but I simply can not do update.

**Comment by Blair2004** [comment]
To encure a better management of your concerns, please consider creating a single isolated issue for every concern you're facing. The reason of this is because, when we work on an issue if that issue is solved, this thread is closed automatically, however when a thread has multiple issues, that doesn't help us solving each gradually. Consider creating a new issue, don't delete the default template as we need you to answer the question that are asked on the template. This helps us to handle better your issue.

Kind Regards.
