### ISSUE TITLE
changing price on pos not working

### ISSUE THREAD

**Issue by abedfatafta** [Blair2004/NexoPOS-4x#386]
when you need to do custom pricing for product in  pos view - on popup numpad the price not changing  just last digit , and not reflected to cart . 
and when you add new item after this try in same cart you get te old product price changed to zero 0

**Comment by Blair2004** [comment]
While creating an issue, do not delete the template provided. Further issues with an invalid format with simply be closed.

Regarding your issue : 
- The numpad starts from the last digits it's not a bug but an intentional behavior, inspired from calculators
![add product](https://user-images.githubusercontent.com/5265663/146138234-3b7c7199-124c-4c86-b1cd-79152f2b84d3.gif)

- I'm not sure to understand what you mean, that's why using the template provided helps to understand better the issue. We've added the same product to the cart, but that product used the original price
![screenshot-nexopos-4x dev-2021 12 15-07_57_56](https://user-images.githubusercontent.com/5265663/146138547-28abc5d8-29f3-4e1d-b871-32c3bc5df5f4.jpg)

An issue with illustrations is far above issue with unclear explanations. We're expecting an update on this issue.

Kind Regards.

**Comment by abedfatafta** [comment]
Thanks for your fast response , 
check your demo  version , i have recorded this by loom ,
https://www.loom.com/share/cec89fc5d5b34d838381a526ce977530.
also the stable version on git have the same problem

**Comment by Blair2004** [comment]
Hi,
Thank you this video. We'll investigate it.

Kind Regards.

**Comment by Blair2004** [comment]
No more applicable (can't be reproduced) to the actual demo http://v4.nexopos.com

**Comment by abedfatafta** [comment]
the demo was 4.6.5 and now its 4.6.6 so its fixed on it ,
