### ISSUE TITLE
**Feature Request ****

### ISSUE THREAD

**Issue by ejazakm** [Blair2004/NexoPOS-4x#459]
**Feature Request**
1. Add Customer limit on customer form, The customer should not be able to buy more than the given credit limit.
2. when the customer buys on account (on account means to buy on credit) when he buys on credit the customer balance should be viewed by the end-user.

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by magedfathi** [comment]
I would like to add one more point related to the same subject which is limit to the due paymnet for each customer.
1- if the customer need to settle his due payment and decided to pay the due amount how the sytem will change the previous payment status from due to paied. 
   i suggest from order we can search by cutomer mobile number and due payment status then multi select all due orders and from action we can make settle the orders then the paid amount will be added to the available limit 
2- can we have seperate report for the due paymnet

**Comment by Blair2004** [comment]
@ejazakm  when you mean the credit should be visible by the end user. Can you show where exactly ?

**Comment by Blair2004** [comment]
![screenshot-78 141 243 3-2022 01 11-12_53_37](https://user-images.githubusercontent.com/5265663/148938067-e11847fa-ab8e-4505-af3d-e4ace4766d7e.jpg)

![screenshot-78 141 243 3-2022 01 11-12_54_27](https://user-images.githubusercontent.com/5265663/148938215-c9cc009e-ea9b-4ad2-9ab3-bb93bc4569a8.jpg)

Added for 4.6.9

**Comment by ejazakm** [comment]
Dera
do you add all feature requested to in new version or not
Ejaz Latweef

**Comment by ejazakm** [comment]
Dear How are you,

Please ignore my last email.
I just want to know, did you implement the above features in the new
release (4.6.9) .
If not, how many days are required for new  features to be added ?

Ejaz Lateef
