### ISSUE TITLE
[Issue] product list search and searchable option issues

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#486]
Hi,
1-searchable option can't be saved while adding or editing product.
2-product list  search didn't work correctly, he didn't give result while we have many products with searched name (chapi as example here) (search method is classic and not autocomplete )
regards
![cha123456](https://user-images.githubusercontent.com/22215705/149042472-5f630c15-2b2e-448f-84e8-5be59976f480.png)
![cha12345](https://user-images.githubusercontent.com/22215705/149042480-1645af23-c63c-4e42-90bf-ffc89b3a751d.png)
![cha1234](https://user-images.githubusercontent.com/22215705/149042481-d6f837cc-31e9-4c7f-941f-0bd7fba902c4.png)
![cha123](https://user-images.githubusercontent.com/22215705/149042482-991f3b89-c621-4637-b346-a84f95718f27.png)
![cha12](https://user-images.githubusercontent.com/22215705/149042486-ab9a8494-700b-4d39-b5bf-09fff5be6776.png)
![cha1](https://user-images.githubusercontent.com/22215705/149042487-871fb82e-1ddd-4ceb-bc13-44d470099a8d.png)
![cha](https://user-images.githubusercontent.com/22215705/149042488-1576b453-1932-44b0-8024-26c08eed4012.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
For upcoming issues, make sure to fill the Environment details at the bottom of the template, your screenshot of the section for screenshot, the expected behavior on his appropriate section. Every issue should be formated the same way to ease our understanding.

Regarding this issue we'll need to take a look at your setup. Unfortunately the environment details are missing. Let us know at contact@nexopos.com
