### ISSUE TITLE
[Issue] Daily Incomplete Orders issue

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#538]
Daily Incomplete Orders issue
**To Reproduce**
1. Go to 'Dashboard'
2. See error

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.11
![Screenshot_2](https://user-images.githubusercontent.com/22215705/151069115-381ca852-40d3-449a-afaa-6e7d67ab3788.png)
![Screenshot (4)](https://user-images.githubusercontent.com/22215705/151069118-08e2348b-f413-4379-a27d-72980ba74ff6.png)
![WhatsApp Image 2022-01-21 at 10 36 31 PM](https://user-images.githubusercontent.com/22215705/151069120-8c1f8877-7b4f-48f9-a8e4-8ce72832bf04.jpeg)

**Comment by Blair2004** [comment]
Hi,
The screenshot doest provide much details about what might be the cause.

Answering those questions might help us :

- Do you have unpaid (incomplete order on your system)?

- what's the value of QUEUE_DRIVER on the .env file.

- Have you don't any action that has affected the report tables ?

if your system is online, please privately on WhatsApp let us know your credentials.

**Comment by boudo2017** [comment]
1-Do you have unpaid (incomplete order on your system)?  yes
2-CACHE_DRIVER=file
QUEUE_CONNECTION=sync
3-cashflow reports have the same issue(total columns amounts)
![Screenshot (4)](https://user-images.githubusercontent.com/22215705/151081197-c19eaf3a-c798-4b4f-a79f-176bb6ee0643.png)

**Comment by Blair2004** [comment]
Please contact us tomorrow (9am - 6pm GMT+1) on WhatsApp we'll checkout your issue on your server.

**Comment by Blair2004** [comment]
After the reviews we've performed on this issue, we weren't able to reproduce this. Due to the limitation on the server, we're not able to properly spot what might cause this. We however believe the issue is caused on NexoPOS codebase by rather the server sending incorrect values to NexoPOS which receives a string where it's expecting a number.

We tested your database + your files on a local and online installation and each time, we weren't able to reproduce the issue. It might therefore cause by a third party app that act as a middleman and overwrite (change) the data transfered from the server to the client. We encourage you choosing another server with the [recommended specifications](https://my.nexopos.com/en/documentation/getting-started/0-requirements)

Kind Regards.

**Comment by boudo2017** [comment]
Hi,
I told you ,I m running many Laraval vue js apps there without issues like this.
That means it caused by wrong code line. Why the other values in the same lines are corrects ?

**Comment by boudo2017** [comment]
as I said:
We have located the logs [2022-02-08 00:20:41] local.INFO: Broadcasting [App\Events\NotificationDeletedEvent] on channels [private-ns.private-channel] with payload:
{
"notification": {
"id": 5,
"user_id": "89",
"identifier": "ns.notifications.cron-disabled",
"title": "Workers Misconfiguration",
"description": "NexoPOS is unable to run tasks correctly. This happens if Queues or Tasks Scheduling aren't configured correctly.",
"url": "https:\/\/laravel.com\/docs\/8.x\/scheduling#starting-the-scheduler",
"source": "system",
"dismissable": "1",
"created_at": "2022-02-08T00:20:41.000000Z",
"updated_at": "2022-02-08T00:20:41.000000Z"
},
"socket": null
}


The issue is located in this code part <h4 class="text-xs text-right">+{{ ( report.day_unpaid_orders + report.day_partially_paid_orders || 0 ) | currency }} {{ __( 'Today' ) }}</h4>



You can locate the code here /home/--------/public_html/-------/resources/ts/pages/dashboard/home/ns-dashboard-cards.vue

**Comment by Blair2004** [comment]
Hi, 
The Workers Misconfiguration is about Queue not the dashboard. Both aren't related. Why the same code line works well on other server ? That's the question.

**Comment by boudo2017** [comment]
ns-dashboard-cards.vue
why there is no the same issues with others apps ?

**Comment by Blair2004** [comment]
The fact is when you deploy the code elsewhere, it works. You've been invited to try deploying locally and we can even deploy your code on our server so you can see the error is not from NexoPOS but as we've explained. Due to the limitation on your hosting as we've explained before there is nothing we can do since it cannot be reproduced.

**Comment by boudo2017** [comment]
why the other values are corrects?
