### ISSUE TITLE
[Issue] I'm having a problem with printing can you help me?

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#717]
1.PROBLEM: HELLO WE ARE USING TURKISH LANGUAGE AFTER CONNECTING TO NEXO PRINT SERVER, THE PRINTS ARE NOT READ AND IT IS WRITTEN IN THIS WAY.
![17cb3a4d-73df-4b42-a4ab-45f4f634f4ec](https://user-images.githubusercontent.com/102427740/164943008-c83b4c2c-7aa8-467d-986e-f4227d4fa14e.jpg)

2. PROBLEM: AFTER SENDING THE PRODUCT TO THE KITCHEN, THE PRINTER I DEFINED ON THE KITCHEN SCREEN DOESN'T EXIT AUTOMATICALLY.

**Comment by Blair2004** [comment]
Hi, once again, your issue is not well formatted. We've pointed you to #501 to see how to create an issue.
Your current thread is lacking useful information such as the version you're using, and with which you're experiencing this.

We believe for upcoming issues, you'll format well your issue. We'll reach you privately to install an experimental solution that might support Turkish characters.
