### ISSUE TITLE
Stuck at login page

### ISSUE THREAD

**Issue by JohnCarlos007** [Blair2004/NexoPOS-4x#88]
Greetings,

I encountered this problem when I finished the installation of NexoPOS in a local server. 
I followed the instructions based on this site: 

https://my.nexopos.com/en/blog/post/how-to-install-nexopos-4-x-on-ubuntu-20-04

The inputted credentials are as follows:

Application: NexoPOS
Username: admin
Email: admin@admin.com
Password: password
Confirm Password: password

I tried to login using these credentials and pressed enter, no redirection happened. Same goes for clicking the Sign In button.
This is the first time I installed this system locally and I am a beginner at this.

**Comment by Blair2004** [comment]
Hi,
Can you provide a video capture ? Or screenshots ?

**Comment by JohnCarlos007** [comment]
Sorry about that here are the screenshots:

This is the sign in page once clicked. 
![image](https://user-images.githubusercontent.com/64250077/99477254-18e94380-298d-11eb-9865-cf9c68cfd6aa.png)
![image](https://user-images.githubusercontent.com/64250077/99477429-72ea0900-298d-11eb-8c18-d1a51856cccd.png)

The command used to run the system is php artisan serve --port=8000 --host=0.0.0.0

Hope this helps.

**Comment by Blair2004** [comment]
Hi, 
Alright, I'll try to reproduce using the provided information. 
Thank you.

**Comment by edis-kujtesa** [comment]
Hi

I was facing the same issue while trying the installation locally. I came here to open a new ticket but since this one is still actual I'll just add my findings here:

1. Firefox gives the following warnings:
`Cookie “XSRF-TOKEN” has been rejected for invalid domain. 127.0.0.1:8000
Cookie “nexopos_4x_session” has been rejected for invalid domain.`

2. Login request header has the entry: 
`X-XSRF-TOKEN | undefined`

3. I get the response:
`{message: "The payload is invalid.", exception: "Illuminate\Contracts\Encryption\DecryptException",…}
exception: "Illuminate\Contracts\Encryption\DecryptException"
file: "C:\wamp64\www\NexoPOS-4x\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php"
line: 195
message: "The payload is invalid."
trace: [,…]`

I hope this helps.

**Comment by Blair2004** [comment]
Hi,
Indeed @edis-kujtesa i've noticed that while using  `php artiasan serve`, [Laravel Sanctum](https://github.com/laravel/sanctum) doesn't define XSRF-TOKEN on header while doing a request to `/sanctum/csrf-token`. It appear that the issue only occurs when the virtual build-in server is being used. Therefore, a workaround would be to create a virtual domain on your apache project in order to serve NexoPOS 4.x. 

As of now, I haven't yet found (exploring Laravel & Sanctum code) what might be the possible cause of this. Please use the suggested workaround.

**Comment by edis-kujtesa** [comment]
@Blair2004 that worked, thank you.

**Comment by Blair2004** [comment]
I believe the situation is solved. Otherwise, feel free to open a new thread.
