### ISSUE TITLE
Increase Quantity of products

### ISSUE THREAD

**Issue by devesh-takoor** [Blair2004/NexoPOS-4x#960]
Hi, I am unable to increase the quantity while uploading a new product, however when I update the quantity of the product from the database it all works good.

Is there a way to increase the quantity directly from the page?
Please advise.
Thank you

**Comment by Blair2004** [comment]
Hi, 
Thank you for your interest. Unfortunately, your issue is not correctly formatted. Make sure to read this #501 
Additionally, as a quick hint, you can't increase/decrease quantity while editing a product, use a procurement instead:

https://www.youtube.com/watch?v=rs2gyBDZrEc
https://my.nexopos.com/en/documentation/components/procurements
